language: java
jdk:
 - oraclejdk8

script: mvn install -DskipTests=true -DTOMCAT_USER=$TOMCAT_USER -DTOMCAT_PASSWORD=TOMCAT_PASSWORD tomcat7:redeploy

notifications:
  email:
    - fab-oger@live.fr
    - iris.courrina@gmail.com
    - lemaire_kevin@hotmail.fr
